server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://tempo:3200/api/;
        proxy_set_header Host $host;
    }

    location /data/ {
        alias /srv/data/;
        add_header Cache-Control "no-cache";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
