// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Slot state machine: a pure reducer implementing the `RequestPhase` lifecycle.
//!
//! The [`RequestPhase::apply`] method takes ownership of the current phase, receives
//! an event, and returns the new phase plus effects. The compiler enforces that every
//! transition handles every resource (staging blocks, ops trackers, etc.).

#![allow(dead_code)]

use std::time::Instant;
use uuid::Uuid;

use crate::block_manager::block::BlockId;
use crate::tokens::{TokenBlock, TokenBlockSequence};

use super::OperationTracker;

// ---------------------------------------------------------------------------
// Supporting types
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DisclosureState {
    Pending,
    Disclosed,
    Consumed,
}

#[derive(Debug)]
pub struct PrefetchState {
    pub operation_id: Uuid,
    pub sequence_hashes: Vec<u64>,
    pub num_external_tokens: usize,
    pub started_at: Instant,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DiagLevel {
    Info,
    Warn,
    Error,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum G4FailPolicy {
    Fallback,
    Abort,
}

impl Default for G4FailPolicy {
    fn default() -> Self {
        Self::Fallback
    }
}

pub struct SlotContext {
    pub block_size: usize,
    pub remote_enabled: bool,
    pub g4_xfer_fail_policy: G4FailPolicy,
}

#[derive(Debug)]
pub struct OffloadRequest {
    pub block_ids: Vec<BlockId>,
    pub priorities: Vec<u32>,
}

// ---------------------------------------------------------------------------
// RequestPhase<H, D>
// ---------------------------------------------------------------------------

/// The single source of truth for request lifecycle. Phase-gated data lives
/// inside variants; no `Option` wrappers for phase-specific resources.
#[derive(Debug)]
pub enum RequestPhase<H, D> {
    /// Just created. No lookup performed.
    Initialized,

    /// Host/disk pool lookup requested. Waiting for results.
    AwaitingLookup,

    /// Async remote registry lookup in flight.
    /// Host/disk blocks from local lookup are carried here.
    LookingUp {
        host_blocks: Vec<H>,
        disk_blocks: Vec<D>,
    },

    /// Remote-to-host prefetch transfer in flight.
    Prefetching {
        prefetch: PrefetchState,
        host_staging: Vec<H>,
        disk_staging: Vec<D>,
        prefetched_blocks_for_stats: usize,
    },

    /// External blocks staged, ready for engine to allocate device blocks.
    OnboardReady {
        num_external_tokens: usize,
        host_staging: Vec<H>,
        disk_staging: Vec<D>,
        remote_hashes: Vec<u64>,
        disclosure: DisclosureState,
        prefetched_blocks_for_stats: usize,
    },

    /// Engine allocated device blocks. Onboarding transfers dispatched.
    Onboarding {
        num_external_tokens: usize,
        ops: OperationTracker,
        started_at: Instant,
    },

    /// Forward pass: prefilling prompt tokens.
    Prefilling {
        iteration_first_scheduled: u64,
    },

    /// Forward pass skipped this step (chunked prefill).
    SkippedPrefill,

    /// Forward pass: generating tokens.
    Decoding {
        ops: OperationTracker,
        iteration_first_scheduled: u64,
    },

    /// Forward pass skipped this step. Carries the ops tracker from Decoding
    /// so in-flight offload transfers are still tracked on resume.
    SkippedDecode {
        ops: OperationTracker,
    },

    /// Request complete but offload transfers still in flight.
    Finishing {
        ops: OperationTracker,
    },

    /// All done. Slot can be removed.
    Finished,

    /// Preempted due to timeout or failure. May retry.
    Preempted {
        recovered_from_failure: bool,
    },
}

// ---------------------------------------------------------------------------
// SlotEvent<H, D>
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub enum SlotEvent<H, D> {
    // --- Lookup (generated by leader internally) ---
    AcquireMatches {
        num_computed_tokens: usize,
    },
    LocalLookupCompleted {
        host_blocks: Vec<H>,
        disk_blocks: Vec<D>,
        remote_candidates: Vec<u64>,
    },
    /// Simplified: uses `(position_hash, remote_key)` tuples instead of the
    /// full `PositionalKey`/`RemoteKey` types to avoid heavy imports.
    RemoteLookupCompleted {
        matches: Vec<(u64, u64)>,
    },
    RemoteLookupClosed,

    // --- Prefetch (generated by leader internally) ---
    PrefetchReady {
        blocks: Vec<H>,
    },
    PrefetchTimeout,
    PrefetchFailed,

    // --- Match reporting (generated by vLLM scheduler poll) ---
    PollMatchReport,

    // --- Allocation (generated by vLLM via update_state_after_alloc) ---
    AllocCompleted {
        block_ids: Vec<BlockId>,
        num_external_tokens: usize,
    },

    // --- Forward pass (generated by vLLM via build_connector_metadata) ---
    ApplySchedulerOutput {
        tokens: Vec<u32>,
        block_ids: Vec<BlockId>,
        num_computed_tokens: usize,
        num_scheduled_tokens: usize,
        priorities: Option<Vec<u32>>,
        iteration: u64,
    },
    MarkSkipped,

    // --- Transfer lifecycle (generated by worker via update_connector_output) ---
    TransferDispatched {
        count: usize,
    },
    TransferCompleted {
        operation_id: Uuid,
    },
    TransferFailed {
        operation_id: Uuid,
    },

    // --- Lifecycle ---
    RequestFinished,
    Preempt,
    Reset,
}

// ---------------------------------------------------------------------------
// SlotEffect<H, D>
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub enum SlotEffect<H, D> {
    // --- I/O delegation ---
    RunLocalLookup {
        num_computed_tokens: usize,
    },
    StartRemoteLookup {
        candidates: Vec<u64>,
        host_blocks: Vec<H>,
        disk_blocks: Vec<D>,
    },
    StartPrefetch {
        hashes: Vec<u64>,
        token_blocks: Vec<TokenBlock>,
        /// Same UUID as [`PrefetchState::operation_id`] and worker `TransferCompleted`.
        operation_id: Uuid,
    },
    EnqueueOnboardTransfer {
        host_staging: Vec<H>,
        disk_staging: Vec<D>,
        remote_hashes: Vec<u64>,
        dst_blocks: Vec<BlockId>,
        num_external_tokens: usize,
    },
    EnqueueOffloadTransfer(OffloadRequest),

    // --- Match reporting ---
    MatchReady {
        num_external_tokens: usize,
    },
    MatchDeferred,
    MatchNone,

    // --- Resource lifecycle ---
    ReleaseStaging,

    // --- Cache stats ---
    RecordCacheStats {
        host_blocks: usize,
        disk_blocks: usize,
        remote_blocks: usize,
        prefetched_blocks: usize,
        total_queried: usize,
    },

    // --- Diagnostics ---
    Diag {
        level: DiagLevel,
        message: String,
    },
}

// ---------------------------------------------------------------------------
// apply() -- the core reducer
// ---------------------------------------------------------------------------

impl<H: std::fmt::Debug, D: std::fmt::Debug> RequestPhase<H, D> {
    /// Pure state-machine reducer. Consumes `self` by value, returns the new
    /// phase and a list of effects for the caller to execute.
    ///
    /// Every `(phase, event)` pair is handled exhaustively. Valid transitions
    /// produce the new phase + effects. Late or irrelevant events are no-ops
    /// that return the phase unchanged.
    pub fn apply(
        self,
        event: SlotEvent<H, D>,
        ctx: &SlotContext,
    ) -> (Self, Vec<SlotEffect<H, D>>) {
        use RequestPhase::*;
        use SlotEvent::*;

        match (self, event) {
            // =============================================================
            // Universal: Reset always returns Initialized.
            // All phase data (staging, ops, prefetch state) is consumed
            // and dropped by the compiler.
            // =============================================================
            (_, Reset) => (Initialized, vec![]),

            // =============================================================
            // Preempt: terminal phases are no-ops
            // =============================================================
            (Finished, Preempt) => (Finished, vec![]),
            (Preempted { recovered_from_failure }, Preempt) => {
                (Preempted { recovered_from_failure }, vec![])
            }

            // Preempt: phases owning staging -- staging consumed and dropped
            (LookingUp { .. }, Preempt) => (
                Preempted {
                    recovered_from_failure: false,
                },
                vec![SlotEffect::ReleaseStaging],
            ),
            (Prefetching { .. }, Preempt) => (
                Preempted {
                    recovered_from_failure: false,
                },
                vec![SlotEffect::ReleaseStaging],
            ),
            (OnboardReady { .. }, Preempt) => (
                Preempted {
                    recovered_from_failure: false,
                },
                vec![SlotEffect::ReleaseStaging],
            ),

            // Preempt: all remaining active phases (no staging to release)
            (_, Preempt) => (
                Preempted {
                    recovered_from_failure: false,
                },
                vec![],
            ),

            // =============================================================
            // Initialized
            // =============================================================
            (Initialized, AcquireMatches { num_computed_tokens }) => (
                AwaitingLookup,
                vec![SlotEffect::RunLocalLookup { num_computed_tokens }],
            ),

            // =============================================================
            // AwaitingLookup
            // =============================================================
            (
                AwaitingLookup,
                LocalLookupCompleted {
                    host_blocks,
                    disk_blocks,
                    remote_candidates,
                },
            ) => {
                if !remote_candidates.is_empty() && ctx.remote_enabled {
                    // Ownership: host/disk blocks move into LookingUp.
                    // The effect carries only the candidates (the host_blocks/disk_blocks
                    // fields exist for the effect signature but are empty here because
                    // the data is owned by the phase).
                    let effects = vec![SlotEffect::StartRemoteLookup {
                        candidates: remote_candidates,
                        host_blocks: vec![],
                        disk_blocks: vec![],
                    }];
                    (LookingUp { host_blocks, disk_blocks }, effects)
                } else if !host_blocks.is_empty() || !disk_blocks.is_empty() {
                    let num_external_tokens =
                        (host_blocks.len() + disk_blocks.len()) * ctx.block_size;
                    (
                        OnboardReady {
                            num_external_tokens,
                            host_staging: host_blocks,
                            disk_staging: disk_blocks,
                            remote_hashes: vec![],
                            disclosure: DisclosureState::Pending,
                            prefetched_blocks_for_stats: 0,
                        },
                        vec![],
                    )
                } else {
                    (Initialized, vec![SlotEffect::MatchNone])
                }
            }

            // =============================================================
            // LookingUp
            // =============================================================
            (
                LookingUp {
                    host_blocks,
                    disk_blocks,
                },
                RemoteLookupCompleted { matches },
            ) => {
                if !matches.is_empty() {
                    let remote_hashes: Vec<u64> =
                        matches.iter().map(|(pos_hash, _)| *pos_hash).collect();
                    let num_external_tokens =
                        (host_blocks.len() + disk_blocks.len() + matches.len()) * ctx.block_size;
                    let operation_id = Uuid::new_v4();
                    let prefetch = PrefetchState {
                        operation_id,
                        sequence_hashes: remote_hashes.clone(),
                        num_external_tokens,
                        started_at: Instant::now(),
                    };
                    let effects = vec![SlotEffect::StartPrefetch {
                        hashes: remote_hashes,
                        token_blocks: vec![], // populated by effect executor
                        operation_id,
                    }];
                    (
                        Prefetching {
                            prefetch,
                            host_staging: host_blocks,
                            disk_staging: disk_blocks,
                            prefetched_blocks_for_stats: matches.len(),
                        },
                        effects,
                    )
                } else {
                    let local_block_count = host_blocks.len() + disk_blocks.len();
                    if local_block_count == 0 {
                        (Initialized, vec![SlotEffect::MatchNone])
                    } else {
                        (
                            OnboardReady {
                                num_external_tokens: local_block_count * ctx.block_size,
                                host_staging: host_blocks,
                                disk_staging: disk_blocks,
                                remote_hashes: vec![],
                                disclosure: DisclosureState::Pending,
                                prefetched_blocks_for_stats: 0,
                            },
                            vec![],
                        )
                    }
                }
            }

            (
                LookingUp {
                    host_blocks,
                    disk_blocks,
                },
                RemoteLookupClosed,
            ) => {
                let local_block_count = host_blocks.len() + disk_blocks.len();
                if local_block_count > 0 {
                    (
                        OnboardReady {
                            num_external_tokens: local_block_count * ctx.block_size,
                            host_staging: host_blocks,
                            disk_staging: disk_blocks,
                            remote_hashes: vec![],
                            disclosure: DisclosureState::Pending,
                            prefetched_blocks_for_stats: 0,
                        },
                        vec![],
                    )
                } else {
                    (Initialized, vec![SlotEffect::MatchNone])
                }
            }

            // =============================================================
            // Prefetching
            // =============================================================
            (
                Prefetching {
                    prefetch,
                    mut host_staging,
                    disk_staging,
                    prefetched_blocks_for_stats,
                },
                PrefetchReady { blocks },
            ) => {
                let new_host_batches = blocks.len();
                host_staging.extend(blocks);
                // If any resolved host blocks were provided, clear
                // remote_hashes to avoid a redundant VAST re-read in
                // EnqueueOnboardTransfer. The host_staging path dispatches
                // fast host→device DMA instead.
                let remote_hashes = if new_host_batches > 0 {
                    vec![]
                } else {
                    prefetch.sequence_hashes
                };
                (
                    OnboardReady {
                        num_external_tokens: prefetch.num_external_tokens,
                        host_staging,
                        disk_staging,
                        remote_hashes,
                        disclosure: DisclosureState::Pending,
                        prefetched_blocks_for_stats,
                    },
                    vec![],
                )
            }

            // v0.18 worker: G4/host prefetch completion is `TransferCompleted` with the same op id
            // as `StartPrefetch` (host blocks already registered — same as PrefetchReady { blocks: [] }).
            (
                Prefetching {
                    prefetch,
                    host_staging,
                    disk_staging,
                    prefetched_blocks_for_stats,
                },
                TransferCompleted { operation_id },
            ) if operation_id == prefetch.operation_id => (
                OnboardReady {
                    num_external_tokens: prefetch.num_external_tokens,
                    host_staging,
                    disk_staging,
                    remote_hashes: prefetch.sequence_hashes,
                    disclosure: DisclosureState::Pending,
                    prefetched_blocks_for_stats,
                },
                vec![],
            ),

            // Staging is consumed and dropped by the compiler.
            (
                Prefetching {
                    prefetch: _,
                    host_staging: _,
                    disk_staging: _,
                    prefetched_blocks_for_stats: _,
                },
                PrefetchTimeout,
            ) => (
                Preempted {
                    recovered_from_failure: false,
                },
                vec![],
            ),

            (
                Prefetching {
                    prefetch: _,
                    host_staging,
                    disk_staging,
                    prefetched_blocks_for_stats: _,
                },
                PrefetchFailed,
            ) => {
                if ctx.g4_xfer_fail_policy == G4FailPolicy::Fallback
                    && (!host_staging.is_empty() || !disk_staging.is_empty())
                {
                    let num_external_tokens =
                        (host_staging.len() + disk_staging.len()) * ctx.block_size;
                    (
                        OnboardReady {
                            num_external_tokens,
                            host_staging,
                            disk_staging,
                            remote_hashes: vec![],
                            disclosure: DisclosureState::Pending,
                            prefetched_blocks_for_stats: 0,
                        },
                        vec![SlotEffect::Diag {
                            level: DiagLevel::Warn,
                            message: "Prefetch failed; falling back to local staging".into(),
                        }],
                    )
                } else {
                    // All staging consumed and dropped.
                    (
                        Preempted {
                            recovered_from_failure: true,
                        },
                        vec![SlotEffect::Diag {
                            level: DiagLevel::Warn,
                            message: "Prefetch failed with no local staging; \
                                      will fall back to full prefill"
                                .into(),
                        }],
                    )
                }
            }

            // =============================================================
            // OnboardReady
            // =============================================================

            // First disclosure: Pending -> Disclosed
            (
                OnboardReady {
                    num_external_tokens,
                    host_staging,
                    disk_staging,
                    remote_hashes,
                    disclosure: DisclosureState::Pending,
                    prefetched_blocks_for_stats,
                },
                PollMatchReport,
            ) => (
                OnboardReady {
                    num_external_tokens,
                    host_staging,
                    disk_staging,
                    remote_hashes,
                    disclosure: DisclosureState::Disclosed,
                    prefetched_blocks_for_stats,
                },
                vec![SlotEffect::MatchReady { num_external_tokens }],
            ),

            // Re-poll after first disclosure: Disclosed -> Consumed (defer once
            // so vLLM processes the first MatchReady before we re-report)
            (
                OnboardReady {
                    num_external_tokens,
                    host_staging,
                    disk_staging,
                    remote_hashes,
                    disclosure: DisclosureState::Disclosed,
                    prefetched_blocks_for_stats,
                },
                PollMatchReport,
            ) => (
                OnboardReady {
                    num_external_tokens,
                    host_staging,
                    disk_staging,
                    remote_hashes,
                    disclosure: DisclosureState::Consumed,
                    prefetched_blocks_for_stats,
                },
                vec![SlotEffect::MatchDeferred],
            ),

            // Subsequent re-polls (Consumed): re-report the match so vLLM
            // can retry allocation when GPU blocks become available.
            // Without this, the slot returns MatchDeferred forever and the
            // request is stuck in WAITING when allocation previously failed.
            (
                OnboardReady {
                    num_external_tokens,
                    host_staging,
                    disk_staging,
                    remote_hashes,
                    disclosure: DisclosureState::Consumed,
                    prefetched_blocks_for_stats,
                },
                PollMatchReport,
            ) => (
                OnboardReady {
                    num_external_tokens,
                    host_staging,
                    disk_staging,
                    remote_hashes,
                    disclosure: DisclosureState::Consumed,
                    prefetched_blocks_for_stats,
                },
                vec![SlotEffect::MatchReady { num_external_tokens }],
            ),

            // Allocation: staging moves out into the onboard-transfer effect
            (
                OnboardReady {
                    num_external_tokens: _,
                    host_staging,
                    disk_staging,
                    remote_hashes,
                    disclosure: _,
                    prefetched_blocks_for_stats: _,
                },
                AllocCompleted {
                    block_ids,
                    num_external_tokens,
                },
            ) => {
                let effects = vec![SlotEffect::EnqueueOnboardTransfer {
                    host_staging,
                    disk_staging,
                    remote_hashes,
                    dst_blocks: block_ids,
                    num_external_tokens,
                }];
                (
                    Onboarding {
                        num_external_tokens,
                        ops: OperationTracker::new(),
                        started_at: Instant::now(),
                    },
                    effects,
                )
            }

            // =============================================================
            // Onboarding
            // =============================================================
            (
                Onboarding {
                    num_external_tokens: _,
                    ops,
                    started_at: _,
                },
                ApplySchedulerOutput { tokens, iteration, .. },
            ) => {
                if tokens.is_empty() {
                    (
                        Prefilling {
                            iteration_first_scheduled: iteration,
                        },
                        vec![],
                    )
                } else {
                    (
                        Decoding {
                            ops,
                            iteration_first_scheduled: iteration,
                        },
                        vec![],
                    )
                }
            }

            // =============================================================
            // Prefilling
            // =============================================================

            // Not in the transition table explicitly, but needed for the
            // "tokens empty = prefilling, tokens present = decoding" contract.
            (
                Prefilling {
                    iteration_first_scheduled,
                },
                ApplySchedulerOutput { tokens, .. },
            ) => {
                if tokens.is_empty() {
                    (
                        Prefilling {
                            iteration_first_scheduled,
                        },
                        vec![],
                    )
                } else {
                    (
                        Decoding {
                            ops: OperationTracker::new(),
                            iteration_first_scheduled,
                        },
                        vec![],
                    )
                }
            }

            (Prefilling { .. }, MarkSkipped) => (SkippedPrefill, vec![]),

            (Prefilling { .. }, RequestFinished) => (
                Finished,
                vec![SlotEffect::RecordCacheStats {
                    host_blocks: 0,
                    disk_blocks: 0,
                    remote_blocks: 0,
                    prefetched_blocks: 0,
                    total_queried: 0,
                }],
            ),

            // =============================================================
            // SkippedPrefill
            // =============================================================
            (SkippedPrefill, ApplySchedulerOutput { tokens, iteration, .. }) => {
                if tokens.is_empty() {
                    (
                        Prefilling {
                            iteration_first_scheduled: iteration,
                        },
                        vec![],
                    )
                } else {
                    (
                        Decoding {
                            ops: OperationTracker::new(),
                            iteration_first_scheduled: iteration,
                        },
                        vec![],
                    )
                }
            }

            (SkippedPrefill, RequestFinished) => (
                Finished,
                vec![SlotEffect::RecordCacheStats {
                    host_blocks: 0,
                    disk_blocks: 0,
                    remote_blocks: 0,
                    prefetched_blocks: 0,
                    total_queried: 0,
                }],
            ),

            // =============================================================
            // Decoding
            // =============================================================
            (
                Decoding {
                    ops,
                    iteration_first_scheduled,
                },
                ApplySchedulerOutput { .. },
            ) => (
                Decoding {
                    ops,
                    iteration_first_scheduled,
                },
                vec![],
            ),

            (Decoding { ops, .. }, MarkSkipped) => {
                if ops.has_any() {
                    tracing::debug!(
                        pending = ops.pending_count(),
                        dispatched = ops.dispatched_count(),
                        "MarkSkipped during Decoding with outstanding ops (carried into SkippedDecode)"
                    );
                }
                (SkippedDecode { ops }, vec![])
            }

            (
                Decoding {
                    ops,
                    iteration_first_scheduled: _,
                },
                RequestFinished,
            ) => {
                if ops.has_any() {
                    (Finishing { ops }, vec![])
                } else {
                    // Counts are zero here -- the effect executor reads
                    // the real values from the slot's cross-phase counters
                    // when executing RecordCacheStats.
                    (Finished, vec![SlotEffect::RecordCacheStats {
                        host_blocks: 0,
                        disk_blocks: 0,
                        remote_blocks: 0,
                        prefetched_blocks: 0,
                        total_queried: 0,
                    }])
                }
            }

            (
                Decoding {
                    mut ops,
                    iteration_first_scheduled,
                },
                TransferCompleted { .. },
            ) => {
                ops.complete_one();
                (
                    Decoding {
                        ops,
                        iteration_first_scheduled,
                    },
                    vec![],
                )
            }

            (
                Decoding {
                    mut ops,
                    iteration_first_scheduled,
                },
                TransferFailed { operation_id },
            ) => {
                ops.complete_one();
                (
                    Decoding {
                        ops,
                        iteration_first_scheduled,
                    },
                    vec![SlotEffect::Diag {
                        level: DiagLevel::Warn,
                        message: format!("Transfer {} failed during decoding", operation_id),
                    }],
                )
            }

            (
                Decoding {
                    ops,
                    iteration_first_scheduled,
                },
                TransferDispatched { .. },
            ) => (
                Decoding {
                    ops,
                    iteration_first_scheduled,
                },
                vec![],
            ),

            // =============================================================
            // SkippedDecode
            // =============================================================
            (SkippedDecode { ops }, ApplySchedulerOutput { iteration, .. }) => (
                Decoding {
                    ops,
                    iteration_first_scheduled: iteration,
                },
                vec![],
            ),

            // =============================================================
            // Finishing
            // =============================================================
            (Finishing { mut ops }, TransferCompleted { .. }) => {
                ops.complete_one();
                if !ops.has_any() {
                    (
                        Finished,
                        vec![SlotEffect::RecordCacheStats {
                            host_blocks: 0,
                            disk_blocks: 0,
                            remote_blocks: 0,
                            prefetched_blocks: 0,
                            total_queried: 0,
                        }],
                    )
                } else {
                    (Finishing { ops }, vec![])
                }
            }

            (Finishing { mut ops }, TransferFailed { operation_id }) => {
                ops.complete_one();
                let mut effects = vec![SlotEffect::Diag {
                    level: DiagLevel::Warn,
                    message: format!(
                        "Transfer {} failed during finishing",
                        operation_id
                    ),
                }];
                if !ops.has_any() {
                    effects.push(SlotEffect::RecordCacheStats {
                        host_blocks: 0,
                        disk_blocks: 0,
                        remote_blocks: 0,
                        prefetched_blocks: 0,
                        total_queried: 0,
                    });
                    (Finished, effects)
                } else {
                    (Finishing { ops }, effects)
                }
            }

            (Finishing { ops }, TransferDispatched { .. }) => (Finishing { ops }, vec![]),

            // =============================================================
            // Preempted
            // =============================================================
            (Preempted { .. }, AcquireMatches { num_computed_tokens }) => (
                AwaitingLookup,
                vec![SlotEffect::RunLocalLookup { num_computed_tokens }],
            ),

            // =============================================================
            // Initialized + ApplySchedulerOutput: cold-start path for
            // cache-miss requests that skip the onboarding flow entirely.
            // Without this, the slot stays Initialized forever and never
            // reaches Decoding (where offload effects are produced).
            //
            // No offload effects here: the forward pass hasn't computed
            // any KV data yet (evaluated_blocks == 0). Offloads fire on
            // subsequent (Decoding, ApplySchedulerOutput) transitions
            // after blocks have been evaluated.
            // =============================================================
            (Initialized, ApplySchedulerOutput { tokens, iteration, .. }) => {
                if tokens.is_empty() {
                    (Prefilling { iteration_first_scheduled: iteration }, vec![])
                } else {
                    (
                        Decoding {
                            ops: OperationTracker::new(),
                            iteration_first_scheduled: iteration,
                        },
                        vec![],
                    )
                }
            }

            // =============================================================
            // Catch-all: late or irrelevant events -- no-op.
            // Each phase variant is listed explicitly to reconstruct owned
            // data (unit variants are trivially reconstructed).
            // =============================================================
            (Initialized, _) => (Initialized, vec![]),
            (AwaitingLookup, _) => (AwaitingLookup, vec![]),
            (LookingUp { host_blocks, disk_blocks }, _) => {
                (LookingUp { host_blocks, disk_blocks }, vec![])
            }
            (
                Prefetching {
                    prefetch,
                    host_staging,
                    disk_staging,
                    prefetched_blocks_for_stats,
                },
                _,
            ) => (
                Prefetching {
                    prefetch,
                    host_staging,
                    disk_staging,
                    prefetched_blocks_for_stats,
                },
                vec![],
            ),
            (
                OnboardReady {
                    num_external_tokens,
                    host_staging,
                    disk_staging,
                    remote_hashes,
                    disclosure,
                    prefetched_blocks_for_stats,
                },
                _,
            ) => (
                OnboardReady {
                    num_external_tokens,
                    host_staging,
                    disk_staging,
                    remote_hashes,
                    disclosure,
                    prefetched_blocks_for_stats,
                },
                vec![],
            ),
            (Onboarding { num_external_tokens, ops, started_at }, _) => {
                (Onboarding { num_external_tokens, ops, started_at }, vec![])
            }
            (Prefilling { iteration_first_scheduled }, _) => {
                (Prefilling { iteration_first_scheduled }, vec![])
            }
            (SkippedPrefill, _) => (SkippedPrefill, vec![]),
            (Decoding { ops, iteration_first_scheduled }, _) => {
                (Decoding { ops, iteration_first_scheduled }, vec![])
            }
            (SkippedDecode { ops }, _) => (SkippedDecode { ops }, vec![]),
            (Finishing { ops }, _) => (Finishing { ops }, vec![]),
            (Finished, _) => (Finished, vec![]),
            (Preempted { recovered_from_failure }, _) => {
                (Preempted { recovered_from_failure }, vec![])
            }
        }
    }
}

// ---------------------------------------------------------------------------
// SlotState compatibility view
// ---------------------------------------------------------------------------

impl<H: std::fmt::Debug, D: std::fmt::Debug> RequestPhase<H, D> {
    /// Derive the legacy [`SlotState`](super::SlotState) from the current phase.
    /// Internal lookup/prefetch phases map to `Initialized` since the old model
    /// did not distinguish them.
    pub fn as_slot_state(&self) -> super::SlotState {
        match self {
            Self::Initialized => super::SlotState::Initialized,
            Self::AwaitingLookup | Self::LookingUp { .. } | Self::Prefetching { .. } => {
                super::SlotState::Initialized
            }
            Self::OnboardReady {
                num_external_tokens,
                ..
            } => super::SlotState::OnboardStaged(*num_external_tokens),
            Self::Onboarding {
                num_external_tokens,
                ..
            } => super::SlotState::Onboarding(*num_external_tokens),
            Self::Prefilling { .. } => super::SlotState::Prefilling,
            Self::SkippedPrefill => super::SlotState::SkippedPrefill,
            Self::Decoding { .. } => super::SlotState::Decoding,
            Self::SkippedDecode { .. } => super::SlotState::SkippedDecode,
            Self::Finishing { .. } => super::SlotState::Finishing,
            Self::Finished => super::SlotState::Finished,
            Self::Preempted { .. } => super::SlotState::Preempted,
        }
    }
}

// ---------------------------------------------------------------------------
// ConnectorSlot<H, D>
// ---------------------------------------------------------------------------

/// The refactored slot struct. Phase-gated data lives inside `RequestPhase`
/// variants. Cross-phase metadata (counters, policy, tracing) lives here.
pub struct ConnectorSlot<H: std::fmt::Debug, D: std::fmt::Debug> {
    // === Identity (immutable after init) ===
    pub request_id: String,
    pub generation: u64,
    pub sequence: TokenBlockSequence,
    pub block_size: usize,

    // === The state machine ===
    phase: RequestPhase<H, D>,

    // === Forward-pass bookkeeping ===
    pub device_blocks: Vec<BlockId>,
    pub current_position: usize,
    pub evaluated_blocks: usize,

    // === Offload policy ===
    pub offload_min_priority: u32,
    pub offload_terminated_at_block: Option<usize>,
    pub g1_residency_unprotected: bool,

    // === Cache statistics (write-only counters) ===
    pub tokens_cached_from_device: usize,
    pub tokens_cached_from_host: usize,
    pub tokens_cached_from_disk: usize,
    pub tokens_cached_from_remote: usize,
    pub total_blocks_queried: usize,
    pub performed_cache_lookup: bool,

    // === Remote tier retry policy ===
    pub remote_retry_count: u32,
    pub remote_skip_on_retry: bool,

    // === Observability ===
    pub traceparent: Option<String>,
    pub baggage: Option<String>,
}

impl<H: std::fmt::Debug, D: std::fmt::Debug> ConnectorSlot<H, D> {
    pub fn phase(&self) -> &RequestPhase<H, D> {
        &self.phase
    }

    /// Takes the current phase out, replacing it with `Initialized`.
    /// Caller must call [`set_phase`] with the new phase before the next event.
    pub fn take_phase(&mut self) -> RequestPhase<H, D> {
        std::mem::replace(&mut self.phase, RequestPhase::Initialized)
    }

    pub fn set_phase(&mut self, phase: RequestPhase<H, D>) {
        self.phase = phase;
    }

    /// Legacy compatibility: derive [`SlotState`](super::SlotState) from the
    /// current [`RequestPhase`].
    pub fn state(&self) -> super::SlotState {
        self.phase.as_slot_state()
    }
}

impl<H: std::fmt::Debug, D: std::fmt::Debug> std::fmt::Debug for ConnectorSlot<H, D> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ConnectorSlot")
            .field("request_id", &self.request_id)
            .field("generation", &self.generation)
            .field("phase", &self.phase)
            .field("device_blocks", &self.device_blocks.len())
            .field("current_position", &self.current_position)
            .finish_non_exhaustive()
    }
}
